### ISSUE TITLE
Editing only my posts 

### ISSUE THREAD

**Issue by paragbaxi** [WojciechMatuszewski/next-appsync-cdk#1]
Thank you for this! I would be grateful if you could share how to only allow posts to be edited or deleted if owned by the authenticated user. I see that the post has a user associated with it. What I do not know is how to consistently store the user to what cognito auth pool provides.

Another way that is less confusing to describe it is, how do I make a graphql query to check if a user created object is created by the logged in user.

**Comment by WojciechMatuszewski** [comment]
Cognito exposes various triggers that you can use to fire lambda function where you save the users' data to a database eg. dynamodb. [Here is the link to docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html). This is how you would save users data that normally is stored in cognito.

When it comes to deleting/editing only my own posts. You could use [dynamoDB condition expressions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html#Expressions.ConditionExpressions.AdvancedComparisons) to check if the userId of the user that is currently making a query matches the userId for a given post.

So let's imagine a POST is saved as follows

| PK          | SK          | Attributes |
|-------------|-------------|------------|
| POST#postId | USER#userId | Attributes |

Then upon `deleteItem` I would use the condition expression that the `SK` is equal `USER#USER_THAT_TRIES_TO_DELETE_ID`.


As for the repo itself, it's a total mess at the moment because I was playing around and learning stuff. Tbh writing vtl templates with single table design is a bit cumbersome, but I definitely learned a ton. 
I would not count on me implementing this feature tho, but feel free to reach with other questions.

**Comment by paragbaxi** [comment]
found a way client side:
```
componentDidMount = async () => {
        this.getPosts()

        await Auth.currentUserInfo()
            .then(user => {
                this.setState(
                    {
                        ownerId: user.attributes.sub,
                        ownerUsername: user.username,
                    }
                )
            })

...
render() {
let loggedInUser = this.state.ownerId
...
{post.postOwnerId === loggedInUser &&
                            <DeletePost data={post}/>
                        }
                         
                        { post.postOwnerId === loggedInUser &&
                           <EditPost {...post} />
                        }
```
